repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: poetry run ruff check --fix .
        require_serial: true
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        language: system
        entry: poetry run ruff format .
        require_serial: true
        pass_filenames: false
